### ISSUE TITLE
Tuple input value is not parsed in "Write Contract"

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1432]
### Description

![image (13)](https://github.com/blockscout/frontend/assets/4341812/9e5ae5c0-6050-40b8-84e1-1d727414ea54)
![image (12)](https://github.com/blockscout/frontend/assets/4341812/d2a8c0f9-c6e6-43c7-a349-354d57fd47c7)

### Link to the page

https://eth-sepolia.blockscout.com/address/0x0174b6E70b51C739ADb0D6d6c50eA49789FB5028?tab=write_contract

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.20.0

### Operating system

None

**Comment by tom2drum** [comment]
will be fixed as part of #1035

**Comment by jaymod** [comment]
This issue is still present for nested tuples in builds after [PR 1413](https://github.com/blockscout/frontend/pull/1413).

Repro:
1. Navigate to https://eth-sepolia.blockscout.com/address/0xc7F957c37193648D087E691016De9542273Be164?tab=contact_code but using a build containing the PR 1413 fix such as https://github.com/blockscout/frontend/pkgs/container/frontend/164130158.
2. Note that the contract contains nested structs (tuples) in the input parameter to the `updateFields` function.
3. With the changes from PR 1413, the top-level tuple fields are split into their own form fields which works great. Unfortunately, the nested tuple fields are not expanded and still suffer from the same input validation issue as is captured in this ticket.

<img width="1202" alt="Screenshot 2024-01-16 at 4 11 37 PM" src="https://github.com/blockscout/frontend/assets/138897/e332cf57-1e5b-4ff1-93d8-9e42ac14a6ce">

Taking a look at the original input validation ticket (https://github.com/blockscout/frontend/issues/1035), arrays are noted as being nestable but the requirement is missing for tuples.

**Comment by tom2drum** [comment]
Hi @jaymod. You're right, we don't support nested fields since it wasn't part of the initial task. However, we've implemented client-side validation for simple values, which should cover most use cases. For the nested structure, you can pass it as a string representation and the underlying library (`viem`) will handle the parsing.

**Comment by jaymod** [comment]
Thanks for the quick reply! Entering a string representation for nested structs works for our use case, but what is the expected format? I tried several variations and always received a `Error: Cannot convert undefined to a Bigint` error. I also could not find any details about the expected format in the documentation. Are you able to successfully write the `nested` field in the above contract?

**Comment by tom2drum** [comment]
Oh, yeah, there is a bug actually, causing it to malfunction currently. I have opened a new issue for it at https://github.com/blockscout/frontend/issues/1512.

**Comment by jaymod** [comment]
Awesome thanks! That's what we're seeing as well.
