### ISSUE TITLE
Multi chain balance button

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1802]
[PRODUCT TASK
](https://www.notion.so/blockscout/Multi-chain-balance-button-7da84bc805404d4c9f4e9ba23849e061?pvs=4)

## What to do? 

We need to add a new multi-chain balance button for an EOA address page
More info in [the product task](https://www.notion.so/blockscout/Multi-chain-balance-button-7da84bc805404d4c9f4e9ba23849e061?pvs=4)

**Comment by maikReal** [comment]
**UPD 12.04:**
Waiting for the proxy from the backend team: 
- https://github.com/orgs/blockscout/projects/8/views/1?pane=issue&itemId=59537614

**Comment by maikReal** [comment]
@isstuev Updated the task, we can continue to work on it. Check details in the product task in Notion

**Comment by isstuev** [comment]
added a variable NEXT_PUBLIC_MULTICHAIN_PROVIDER_CONFIG={'name': 'zerion', 'url': 'zerion', 'logo': 'https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/marketplace-logos/zerion.svg'}

'name' and 'logo' are for the button content
'url' can be a full url or an app id in our marketplace. In the latter case marketplace should be configured for the instance, otherwise multi chain feature would be  disabled.
